---
# tasks file for common_services

- name: Install required packages (OS specific)
  package:
    name: >-
      {{
        (install_packages           | default([])) +
        (install_packages_os_common | default([]))
      }}
    state: present
  become: true
