---
# tasks file for burpsuite

- name: Récupérer la liste des releases stables de Burp
  uri:
    url: "{{ burp_releases_url }}"
    method: GET
    return_content: yes
  register: burp_json

- name: Extraire la version et le lien du dernier JAR Community Edition
  set_fact:
    burp_latest_item: "{{ (burp_json.content | from_json).ResultSet.Results[0].version }}"


- name: Show burpsuite version
  debug:
    msg: "Burp Suite Community Edition version {{ burp_latest_item }}"

- name: Télécharger le dernier Burp Suite Community JAR
  get_url:
    url: "https://portswigger.net/burp/releases/download?product=community&version={{ burp_latest_item }}&type=Jar"
    dest: "/usr/local/lib/burpsuite-community-latest.jar"
    mode: '0755'
  become: true

- name: Ajouter un script launcher dans /usr/local/bin
  copy:
    dest: /usr/local/bin/burpsuite
    content: |
      #!/bin/sh
      exec java -jar /usr/local/lib/burpsuite-community-latest.jar "$@"
    mode: "0755"
  become: true
