---
# tasks file for burpsuite

- name: Récupérer la liste des releases stables de Burp
  uri:
    url: "{{ burp_releases_url }}"
    method: GET
    return_content: yes
  register: burp_json

#- name: Extraire URL et version du dernier JAR Community Edition stable
#  set_fact:
#    burp_latest_version: "{{ item.builds[0].Version }}"
#    burp_latest_jar_url: "https://portswigger.net/burp/releases/download?product=community&version={{ item.builds[0].Version }}&type=Jar"
#  loop: "{{ (burp_json.content | from_json).ResultSet.Results }}"
#  when: >
#    ("Community" in item.categories) and
#    (item.builds | selectattr('ProductPlatform', 'equalto', 'Jar') | list | length > 0) and
#    (item.builds | selectattr('ProductId', 'equalto', 'community') | list | length > 0)
#  loop_control:
#    label: "{{ item.builds[0].Version }}"
#  register: burp_latest_info
#  until: burp_latest_version is defined
#  retries: 5
#  delay: 2

- name: Extraire la version et le lien du dernier JAR Community Edition
  set_fact:
    burp_latest_item: "{{ (burp_json.content | from_json).ResultSet.Results[0].version }}"


- name: (Optionnel) Afficher la version installée
  debug:
    msg: "Burp Suite Community Edition version {{ burp_latest_item }} installée dans /opt/burpsuite-community-latest.jar"

- name: Télécharger le dernier Burp Suite Community JAR
  get_url:
    url: "https://portswigger.net/burp/releases/download?product=community&version={{ burp_latest_item }}&type=Jar"
    dest: "/opt/burpsuite-community-latest.jar"
    mode: '0755'
  become: true

- name: Ajouter un script launcher dans /usr/local/bin
  copy:
    dest: /usr/local/bin/burpsuite-community
    content: |
      #!/bin/sh
      exec java -jar /opt/burpsuite-community-latest.jar "$@"
    mode: "0755"
  become: true
