---
# tasks file for meta-offsec-ad

- name: Install required packages (common for all OS)
  package:
    name: "{{ install_packages | flatten }}"
    state: present
  become: true

- name: install pipx tools
  community.general.pipx:
    name: "{{ item }}"
    state: present
  with_items: "{{ install_pipx_tools | default([]) }}"
  when: install_pipx_tools is defined and install_pipx_tools | length > 0
  become: true
  become_user: "{{ default_username }}"

