---
# tasks file for user_env

- name: copy user environment files
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/"
    dest: "/home/{{ default_username }}/"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
  become: true
  become_user: "{{ default_username }}"

# --- zsh ------------------------------------------------

# set user default shell as zsh
- name: set user default shell as zsh
  ansible.builtin.user:
    name: "{{ default_username }}"
    shell: /bin/zsh
  become: true

# --- ruby ------------------------------------------------

# - name: bundle set path
#  command: "bundle config path vendor/"

# https://wiki.archlinux.org/title/RVM#Using_RVM
# - name: get install script for rvm
#  shell: "curl -L https://get.rvm.io | bash"


- include_tasks: config-arsenal.yaml
- include_tasks: config-taskwarrior.yaml
- include_tasks: config-vim.yaml
