---
# tasks file for user_env

# --- tmux ------------------------------------------------

- name: set tmux configuration
  ansible.builtin.copy:
    src: tmux/tmux.conf
    dest: "/home/{{ default_username }}/.tmux.conf"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
  become: true
  become_user: "{{ default_username }}"

# --- (neo)vim ------------------------------------------------

# nvim config
- name: Clone LazyVim starter config
  ansible.builtin.git:
    repo: https://github.com/LazyVim/starter
    dest: "/home/{{ default_username }}/.config/nvim"
    depth: 1
    update: no
  become: true
  become_user: "{{ default_username }}"

- name: remove default init.lua
  ansible.builtin.file:
    path: "/home/{{ default_username }}/.config/nvim/init.lua"
    state: absent
    force: yes
  become: true
  become_user: "{{ default_username }}"

- name: replace default init.lua with custom one
  ansible.builtin.copy:
    src: vim/init.lua
    dest: "/home/{{ default_username }}/.config/nvim/init.lua"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
  become: true
  become_user: "{{ default_username }}"

- name: Sync LazyVim plugins
  ansible.builtin.command:
    cmd: nvim --headless +"Lazy! sync" +qa
  become: true
  become_user: "{{ default_username }}"
  environment:
    HOME: "/home/{{ default_username }}"
  register: lazyvim_sync
  changed_when: false

# --- ruby ------------------------------------------------

# - name: bundle set path
#  command: "bundle config path vendor/"

# https://wiki.archlinux.org/title/RVM#Using_RVM
# - name: get install script for rvm
#  shell: "curl -L https://get.rvm.io | bash"
