---
# tasks file for user_env

- name: copy user environment files
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/"
    dest: "/home/{{ default_username }}/"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
  become: true
  become_user: "{{ default_username }}"

- name: clean user home
  ansible.builtin.file:
    path: "/home/{{ default_username }}/{{ link_item }}"
    state: absent
  loop:
    - .zshrc
  loop_control:
    loop_var: link_item
  become: true


- name: setup user home links to resources
  ansible.builtin.file:
    src: "/opt/resources/res/home_volund/{{ link_item }}"
    dest: "/home/{{ default_username }}/{{ link_item }}"
    state: link
  loop:
    - .config
    - .p10k.zsh
    - .taskrc
    - .tmux.conf
    - .zshrc
  loop_control:
    loop_var: link_item
  become: true
  become_user: "{{ default_username }}"


# --- zsh ------------------------------------------------

# set user default shell as zsh
- name: set user default shell as zsh
  ansible.builtin.user:
    name: "{{ default_username }}"
    shell: /bin/zsh
  become: true

# --- ruby ------------------------------------------------

# - name: bundle set path
#  command: "bundle config path vendor/"

# https://wiki.archlinux.org/title/RVM#Using_RVM
# - name: get install script for rvm
#  shell: "curl -L https://get.rvm.io | bash"


- include_tasks: config-arsenal.yaml
- include_tasks: config-taskwarrior.yaml
- include_tasks: config-vim.yaml
