---

# --- arsenal ------------------------------------------------

- name: Enable legacy TIOCSTI for dev.tty
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: "dev.tty.legacy_tiocsti=1"
    state: present
    create: yes
  become: true

- name: Update CHEATS_PATHS in /opt/arsenal/arsenal/modules/config.py (reduced version)
  ansible.builtin.replace:
    path: /opt/arsenal/arsenal/modules/config.py
    regexp: 'CHEATS_PATHS\s*=\s*\[[^\]]*\]'
    replace: |
      CHEATS_PATHS = [
      {% if arsenal_config_mode == "full" -%}
          join(DATAPATH, "cheats"),  # DEFAULT
      {% else -%}
          join(DATAPATH, "cheats", "Archive"),
          join(DATAPATH, "cheats", "Cloud"),
          join(DATAPATH, "cheats", "Crypto"),
          join(DATAPATH, "cheats", "Databases"),
          join(DATAPATH, "cheats", "Files"),
          join(DATAPATH, "cheats", "Install"),
          join(DATAPATH, "cheats", "Linux"),
          join(DATAPATH, "cheats", "Services"),
          join(DATAPATH, "cheats", "Tools"),
          join(DATAPATH, "cheats", "Windows"),
      {% endif %}
          # Additional paths below, add comma to line above
          join(BASEPATH, "my_cheats"),
          join(HOMEPATH, ".cheats"),
          # Volund folders
          "/usr/share/arsenal-cheats",
          "/opt/resources/res/arsenal-cheats",
          "/opt/my-resources/res/arsenal-cheats"
      ]
  become: true
