---

# --- oh-my-zsh ------------------------------------------------

- name: Download ohmyzsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "/home/{{ default_username }}/install.sh"
    mode: '0755'
  become: true
  become_user: "{{ default_username }}"

# if folder .oh-my-zsh already exist, do not redo install
- name: Install ohmyzsh
  ansible.builtin.script:
    cmd: "/home/{{ default_username }}/install.sh"
  become: true
  become_user: "{{ default_username }}"
  args:
    creates: "/home/{{ default_username }}/.oh-my-zsh"

# remove install file after install
- name: remove ohmyzsh install file
  ansible.builtin.file:
    path: "/home/{{ default_username }}/install.sh"
    state: absent
  become: true

- name: execute test commands
  include_tasks: "{{ role_path }}/../../custom_steps/github_download_code_zip.yaml"
  vars:
    owner: romkatv
    repo: powerlevel10k
    local_path: "/home/{{ default_username }}/.oh-my-zsh/custom/themes/powerlevel10k"
    as_user: "{{ default_username }}"
