---

- name: Install required packages (common for all OS)
  package:
    name: "{{ install_packages_os_common | flatten }}"
    state: present

- name: install helm plugin unittest
  become: false
  ansible.builtin.command:
    cmd: helm plugin install https://github.com/helm-unittest/helm-unittest.git
    chdir: "{{ ansible_env.HOME }}"
  environment:
    USER: "{{ default_username }}"

- name: Install OpenShift CLI (oc)
  ansible.builtin.get_url:
    url: "{{ oc_client_url }}"
    dest: /tmp/openshift-client-linux.tar.gz
  become: true

- name: Extract oc binary
  ansible.builtin.unarchive:
    src: /tmp/openshift-client-linux.tar.gz
    dest: /usr/local/bin/
    remote_src: true
    creates: /usr/local/bin/oc
  become: true

- name: Ensure oc binary is executable
  ansible.builtin.file:
    path: /usr/local/bin/oc
    mode: '0755'
  become: true
