---

- name: Install required packages (common for all OS)
  package:
    name: "{{ install_packages | flatten }}"
    state: present
  become: true

# === argocd cli ==========================================

- name: download argocd artifact from github
  include_tasks: "{{ role_path }}/../../custom_steps/github_download_artifact.yaml"
  vars:
    owner: argoproj
    repo: argo-cd
    local_path: "{{ volund_temp_folder }}/argocd"
    artifact_name_prefix: argocd-linux-
    artifact_name_suffix: amd64

- name: Installer le binaire Argo CD CLI
  copy:
    src: "{{ volund_temp_folder }}/argocd"
    dest: "/usr/local/bin/argocd"
    remote_src: yes
    mode: '0555'
  become: true

# === helm ================================================

- name: get latest tag name from github
  include_tasks: "{{ role_path }}/../../custom_steps/github_get_latest_tag.yaml"
  vars:
    owner: helm
    repo: helm

- name: Download and extract Helm
  unarchive:
    src: "https://get.helm.sh/helm-{{ latest_tag }}-linux-{{ binary_arch_name }}.tar.gz"
    dest: "{{ volund_temp_folder }}/"
    remote_src: yes

- name: Installer le binaire Helm
  copy:
    src: "{{ volund_temp_folder }}/linux-{{ binary_arch_name }}/helm"
    dest: "/usr/local/bin/helm"
    mode: '0755'
    remote_src: yes
  become: true

- name: install helm plugin unittest
  ansible.builtin.command:
    cmd: helm plugin list
  register: helm_plugin_list
  become: true
  become_user: "{{ default_username }}"

- name: install helm plugin unittest
  ansible.builtin.command:
    cmd: helm plugin install https://github.com/helm-unittest/helm-unittest.git
  become: true
  become_user: "{{ default_username }}"
  when: helm_plugin_list.stdout is search('^unittest')

# === k9s =================================================

- name: download artifact from github
  include_tasks: "{{ role_path }}/../../custom_steps/github_download_artifact.yaml"
  vars:
    owner: derailed
    repo: k9s
    local_path: "{{ volund_temp_folder }}/"
    as_user: volund  # optional: default to root
    artifact_name_prefix: k9s_Linux
    artifact_name_suffix: "{{ binary_arch_name }}.tar.gz"
    unarchive: true

- name: Installer K9s
  copy:
    src: "{{ volund_temp_folder }}/k9s"
    dest: "/usr/local/bin/k9s"
    mode: '0755'
  become: true

# === kubectl =============================================

- name: Récupérer la dernière version stable de kubectl
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_version

- name: Télécharger kubectl
  get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version.content | trim }}/bin/linux/{{ binary_arch_name }}/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: '0755'
  become: true

# === openshift cli oc ====================================

- name: Download and Extract oc binary
  ansible.builtin.unarchive:
    src: "{{ oc_client_url }}"
    dest: /usr/local/bin/
    remote_src: true
    creates: /usr/local/bin/oc
  become: true

- name: Ensure oc binary is executable
  ansible.builtin.file:
    path: /usr/local/bin/oc
    mode: '0755'
  become: true

# === stern ===============================================

- name: download artifact from github
  include_tasks: "{{ role_path }}/../../custom_steps/github_download_artifact.yaml"
  vars:
    owner: stern
    repo: stern
    local_path: "{{ volund_temp_folder }}"
    artifact_name_prefix: ""
    artifact_name_suffix: "_linux_{{ binary_arch_name }}.tar.gz"
    unarchive:  true

- name: Installer Stern
  copy:
    src: "{{ volund_temp_folder }}/stern"
    dest: "/usr/local/bin/stern"
    mode: '0755'
    remote_src: yes
  become: true
