#SPDX-License-Identifier: MIT-0
---


- name: "{{ ansible_role_name }} :: check requirements"
  block:
    - name: Precheck
      ansible.builtin.include_tasks: precheck.yaml
  when:
    - "'devsecops' in active_profiles"
    - "'check' in active_actions"


- name: "{{ ansible_role_name }} :: Installation"
  block:
    - name: "Install"
      ansible.builtin.include_tasks: install.yaml
  when:
    - "'devsecops' in active_profiles"
    - "'install' in active_actions"


- name: "{{ ansible_role_name }} :: Configuration"
  block:
    - name: "Configuration"
      ansible.builtin.include_tasks: config.yaml
  when:
    - "'devsecops' in active_profiles"
    - "'config' in active_actions"


- name: "{{ ansible_role_name }} :: Hardening"
  block:
    - name: "Hardening"
      ansible.builtin.include_tasks: hardening.yaml
  when:
    - "'devsecops' in active_profiles"
    - "'hardening' in active_actions"


- name: "{{ ansible_role_name }} :: Installation tests"
  block:
    - name: "Testing"
      ansible.builtin.include_tasks: test_exec.yaml
  when:
    - "'devsecops' in active_profiles"
    - "'check' in active_actions"
