---
# tasks file for env_java

- name: Install required packages (common for all OS)
  package:
    name: "{{ install_packages | flatten }}"
    state: present
  #when : install_packages_os_common is defined and install_packages_os_common | length > 0
  become: true
