---

- name: Configuration of container for role devsecops
  hosts: localhost
  gather_facts: true

  vars:
    active_actions: "{{ lookup('env', 'ACTIVE_ACTIONS') | default('') | split(',') }}"


    allowed_actions: ["install", "config", "data", "hardening", "check"]

    # Archlinux: Archlinux, BlackArch
    # Debian: Kali, Debian
    # RedHat: Fedora
    allowed_os_familly: ["Archlinux", "Debian", "hardening", "check"]

    volund_role: devsecops

  pre_tasks:
    - name: include generic pre_task
      ansible.builtin.include_tasks: custom_steps/playbook_pre_tasks.yaml
  
  post_tasks:
    - name: include generic pre_task
      ansible.builtin.include_tasks: custom_steps/playbook_post_tasks.yaml

    # - name: "Ensure active actions are valids"
    #   ansible.builtin.assert:
    #     that: >
    #       active_actions | difference(allowed_actions) | length == 0
    #     fail_msg: "active_actions contain unknown values : {{ active_actions | difference(allowed_actions) }}"

    # - name: Display active actions
    #   ansible.builtin.debug:
    #     msg: "Actions : {{ active_actions | join(', ') }}"
    
    # - name: Include OS-specific variables
    #   ansible.builtin.debug:
    #     msg:
    #       - "OS Familly:   {{ ansible_os_family }}"
    #       - "Distribution: {{ ansible_distribution }}"
    #       - "Version:      {{ ansible_distribution_version }}"
    #       - "Architecture: {{ ansible_architecture}}"

  roles:
    - meta_base
    - meta_devsecops

    
    
    # SAST tools
    # anchore
    # grype
    # kube-bench : bonnes pratiques Kubernetes CIS Benchmark
    # kube-hunter : Kubernetes security assessment tool
    # etc.

    # nuclei ?
    
  # post_tasks:
  #   - name: Display completion message
  #     ansible.builtin.debug:
  #       msg: ✅ Playbook completed successfully!

  #   - name: Display active actions
  #     ansible.builtin.debug:
  #       msg: "Actions : {{ active_actions | join(', ') }}"
