---

- name: Configuration of container for role devsecops
  hosts: localhost
  gather_facts: true

  vars:
    active_actions: "{{ lookup('env', 'ACTIVE_ACTIONS') | default('') | split(',') }}"

    allowed_actions: ["install", "config", "data", "hardening", "check"]

    # Archlinux: Archlinux, BlackArch
    # Debian: Kali, Debian
    # RedHat: Fedora
    allowed_os_familly: ["archlinux", "debian"]

    volund_role: offsec

  pre_tasks:
    - name: include generic pre_task
      ansible.builtin.include_tasks: custom_steps/playbook_pre_tasks.yaml
      vars:
        allowed_distribs: ['blackarch', 'parrot', 'kali']
  
  post_tasks:
    - name: include generic pre_task
      ansible.builtin.include_tasks: custom_steps/playbook_post_tasks.yaml

    # - name: "Ensure active actions are valids"
    #   ansible.builtin.assert:
    #     that: >
    #       active_actions | difference(allowed_actions) | length == 0
    #     fail_msg: "active_actions contain unknown values : {{ active_actions | difference(allowed_actions) }}"

    # - name: Display active actions
    #   ansible.builtin.debug:
    #     msg: "Actions : {{ active_actions | join(', ') }}"
    
    # - name: Include OS-specific variables
    #   ansible.builtin.debug:
    #     msg:
    #       - "OS Familly:   {{ ansible_os_family }}"
    #       - "Distribution: {{ ansible_distribution }}"
    #       - "Version:      {{ ansible_distribution_version }}"
    #       - "Architecture: {{ ansible_architecture}}"

  roles:

    - meta_offsec
    
        # OSINT tools
        # theHarvester
        # recon-ng

        # common enumeration tools
        #- network_scan
        # amass, nmap, masscan, dnsenum, dnsrecon, subfinder, httpx, waybackurls, gauplus

        # networks tools
        # chisel
      
        # vuln DBs
        #- exploitdb

        # vuln scanners
        # nessus / openvas
    
    # web audit
    # - web_audit
    # - burpsuite
    #- caido
        # nikto
        # OWASP ZAP
        # SQLMap
        # XSSstrike
        # ffuf / dirsearch

        # AD audit
        # impacket
        # bloodhound
        # ldapsearch
        # crackmapexec

    # cloud audit
    # - cloud_clients

    # cracking
    # - name: cracking
      # vars:
      #   data_root_path: /opt/data/
        # hydra
        # hashcat
        # cewl

    # C2
    #- metasploit
        # empire
        # sliver

    #- reverse_engineering
    
  # post_tasks:
  #   - name: Display completion message
  #     ansible.builtin.debug:
  #       msg: ✅ Playbook completed successfully!

  #   - name: Display active actions
  #     ansible.builtin.debug:
  #       msg: "Actions : {{ active_actions | join(', ') }}"
