---
# tasks file for web_browser

- name: Install required packages
  package:
    name: "{{ install_packages | flatten }}"
    state: present
  become: true

- name: Install audio packages
  package:
    name: "{{ install_gui_packages_drivers | flatten }}"
    state: present
  become: true
