---
# tasks file for meta-offsec-reverse

- name: execute test commands
  include_tasks: "{{ role_path }}/../../custom_steps/test_applications_exec.yaml"
  vars:
    commands_list: "{{ test_commands }}"
    username: "{{ default_username }}"
  when: test_commands is defined and test_commands | length > 0
