---
# vars file for cracking

install_packages:
  - fcrackzip
  - hashcat
  - hydra
  - john

test_commands: []

dictionary_root_path: "{{ data_root_path }}/wordlists/"

dictionaries_files:
  - name: rockyou
    url: https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt
    path: rockyou.txt

dictionaries_repos:
  - name: PayloadsAllTheThings
    owner: swisskyrepo
    repo: PayloadsAllTheThings
  - name: Fuzzing-Templates
    owner: projectdiscovery
    repo: fuzzing-templates
    branch: main
  - name: BruteX
    owner: 1N3
    repo: BruteX
  - name: IntruderPayloads
    owner: 1N3
    repo: IntruderPayloads
  - name: Probable-Wordlists
    owner: berzerk0
    repo: Probable-Wordlists
  - name: Open-Redirect-Payloads
    owner: cujanovic
    repo: Open-Redirect-Payloads
  - name: SecLists
    owner: danielmiessler
    repo: SecLists
  - name: Pwdb-Public
    owner: ignis-sec
    repo: Pwdb-Public
  - name: Bug-Bounty-Wordlists
    owner: Karanxa
    repo: Bug-Bounty-Wordlists
    branch: main
  - name: richelieu
    owner: tarraschk
    repo: richelieu
  - name: webapp-wordlists
    owner: p0dalirius
    repo: webapp-wordlists
    branch: main
