---
# tasks file for burpsuite

- name: "Create directory for Burp Suite"
  ansible.builtin.file:
    path: "/usr/share/burpsuite"
    state: directory
    mode: '0755'
  become: true

- name: "Check if BurpSuiteCA.der exists"
  stat:
    path: /usr/share/burpsuite/BurpSuiteCA.der
  register: burp_cert

# This script will be purged with the global temp folder
- name: "Copying Burp Script"
  copy:
    src: files/getburpcert.sh
    dest: "{{ volund_temp_folder }}/getburpcert.sh"
    mode: 0744
  become: true
  become_user: "{{ default_username }}"
  when: burp_cert.stat.exists == False

- name: "Executing bash script to Download CA Certificate"
  shell:
    "{{ volund_temp_folder }}/getburpcert.sh"
  become: true
  become_user: "{{ default_username }}"
  when: burp_cert.stat.exists == False
  
- name: "Copying CA Certificate to /opt/burpsuite"
  copy:
    src: /tmp/cacert.der
    dest: /usr/share/burpsuite/BurpSuiteCA.der
    owner: root
    group: root
    mode: 0644
  become: true
  when: burp_cert.stat.exists == False

- name: "Create directory for Burp Suite user config"
  ansible.builtin.file:
    path: "/home/{{ default_username }}/.BurpSuite/"
    state: directory
    mode: '0755'
  become: true
  become_user: "{{ default_username }}"

- name: "Copy BurpSuite Community Config"
  template:
    src: "templates/UserConfigCommunity.json.j2"
    dest: "/home/{{ default_username }}/.BurpSuite/UserConfigCommunity.json"
  become: true
  become_user: "{{ default_username }}"
