---
# tasks file for exploitdb

- name: execute test commands
  include_tasks: "{{ role_path }}/../../custom_steps/git_app.yaml"
  vars:
    repo_url: https://gitlab.com/exploit-database/exploitdb.git
    local_path: /opt/local/exploitdb/
    links: "{{ tools_links }}"
