---

- name: Vérifier la présence des certificats
  stat:
    path: "{{ build_resource_path }}/certs/"
  register: certs_dir

- name: Copier les certificats si sourcePath est défini
  copy:
    src: "{{ build_resource_path }}/certs/"
    dest: "{{ ca_trust_path }}"
    owner: root
    group: root
    mode: '0644'
    remote_src: yes
  when:
    - certs_dir.stat.exists
    - certs_dir.stat.isdir

- name: Mettre à jour le CA trust store
  command: update-ca-trust
  when:
    - certs_dir.stat.exists
    - certs_dir.stat.isdir
    - ansible_os_family in ['redhat']

- name: Mettre à jour le CA trust store
  command: update-ca-certificates
  when:
    - certs_dir.stat.exists
    - certs_dir.stat.isdir
    - certs_dir.stat.mtime > 0
    - ansible_os_family in ['debian']

- name: Mettre à jour le CA trust store
  command: trust extract-compat
  when:
    - certs_dir.stat.exists
    - certs_dir.stat.isdir
    - certs_dir.stat.mtime > 0
    - ansible_os_family in ['Archlinux']
