---

# -- system date & timezone ----------------------------------

- name: Get timezone from ipapi.co if TZ is undefined or empty
  ansible.builtin.uri:
    url: https://ipapi.co/timezone
    return_content: true
  register: timezone_response
  when: TZ is undefined or TZ == None or TZ | length == 0

- name: Set timezone fact
  ansible.builtin.set_fact:
    timezone: "{{ (TZ is defined and TZ != None and TZ | length > 0) | ternary(TZ, timezone_response.content | trim) }}"

- name: Set timezone fact
  ansible.builtin.set_fact:
    timezone: "{{ timezone_response.content | trim }}"

- name: Set system timezone
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    force: true
  become: true

- name: Write timezone to /etc/timezone
  ansible.builtin.copy:
    content: "{{ timezone }}\n"
    dest: /etc/timezone
    owner: root
    group: root
    mode: '0644'
  become: true

# --- profile & user --------------------------------------

# - name: copy profile file
#   ansible.builtin.template:
#     src: "{{ item }}.j2"
#     dest: "/etc/profile.d/{{ item }}"
#     owner: root
#     group: root
#     mode: '0644'
#   loop_control:
#     loop_var: item
#   with_items:
#     - 90-volund.sh
#   become: true


- name: Ajouter contenu template Jinja2 à /etc/zsh/zprofile s'il n'existe pas
  ansible.builtin.blockinfile:
    path: /etc/zsh/zprofile
    block: "{{ lookup('template', '90-volund.sh.j2') }}"
    create: yes
    marker: '# {mark} ANSIBLE BLOCK - Custom zshprofile additions'
  become: true

# --- python ----------------------------------------------

- name: Ensure pipx is initialised for user
  command: pipx ensurepath
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin"
  become: true
  become_user: "{{ default_username }}"

# --- entrypoint -----------------------------------------------

- name: ensure entrypoint.sh is in Unix format
  ansible.builtin.command:
    cmd: "dos2unix /opt/resources/bin/volund_entrypoint.sh"
  become: true
  when: resources_rw is true

- name: Make entrypoint.sh executable
  ansible.builtin.file:
    path: /opt/resources/bin/volund_entrypoint.sh
    mode: '0755'
    owner: "{{ default_username }}"
  become: true
  when: resources_rw is true

- name: Add missing ansible link from pipx
  ansible.builtin.file:
    src: "/home/volund/.local/share/pipx/venvs/ansible/bin/{{ link_item }}"
    dest: "/home/volund/.local/bin/{{ link_item }}"
    state: link
  become: true
  become_user: "{{ default_username }}"
  loop_control:
    loop_var: link_item
  loop:
    - ansible
    - ansible-config
    - ansible-console
    - ansible-doc
    - ansible-galaxy
    - ansible-inventory
    - ansible-playbook
    - ansible-pull
    - ansible-test
    - ansible-vault
