---

# -- system date & timezone ----------------------------------

- name: Get timezone from ipapi.co if TZ is undefined or empty
  ansible.builtin.uri:
    url: https://ipapi.co/timezone
    return_content: true
  register: timezone_response
  when: TZ is undefined or TZ == None or TZ | length == 0

- name: Set timezone fact
  ansible.builtin.set_fact:
    timezone: "{{ (TZ is defined and TZ != None and TZ | length > 0) | ternary(TZ, timezone_response.content | trim) }}"

- name: Set timezone fact
  ansible.builtin.set_fact:
    timezone: "{{ timezone_response.content | trim }}"

- name: Set system timezone
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    force: true
  become: true

- name: Write timezone to /etc/timezone
  ansible.builtin.copy:
    content: "{{ timezone }}\n"
    dest: /etc/timezone
    owner: root
    group: root
    mode: '0644'
  become: true

# --- profile & user --------------------------------------

- name: copy profile file
  ansible.builtin.template:
    src: profile.volund.sh.j2
    dest: /etc/profile.d/90-volund.sh
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Create default user
  ansible.builtin.user:
    name: "{{ default_username }}"
    uid: "{{ default_user_UID }}"
    shell: "{{ default_user_shell }}"
    groups: sudo
    append: true
    state: present
  when: ansible_os_family in ['Debian']
  become: true

- name: Create default user
  user:
    name: "{{ default_username }}"
    uid: "{{ default_user_UID }}"
    shell: "{{ default_user_shell }}"
    groups: wheel
    append: true
    state: present
  when: ansible_os_family in ['Archlinux', 'RedHat']
  become: true

- name: Set sudo to NOPASSWD for this user
  lineinfile:
    path: /etc/sudoers
    line: "{{ default_username }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
  when: ansible_os_family in ['Debian', 'RedHat']
  become: true

- name: Set sudo to NOPASSWD for this user (wheel group)
  lineinfile:
    path: /etc/sudoers
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
  when: ansible_os_family in ['Archlinux']
  become: true

# --- ca-certificates -----------------------------------------

- name: Check presence of certificates files
  stat:
    path: "{{ build_resource_path }}/certs/"
  register: certs_dir

- name: Deploy custom CA certificates directory
  block:
    - name: Copy certs if sourcePath is defined
      copy:
        src: "{{ build_resource_path }}/certs/"
        dest: "{{ ca_trust_path }}"
        owner: root
        group: root
        mode: '0644'
        remote_src: true

    - name: Update CA trust store
      command: update-ca-trust
      when:
        - ansible_os_family in ['RedHat']

    - name: Update CA trust store
      command: update-ca-certificates
      when:
        - ansible_os_family in ['Debian']

    - name: Update CA trust store
      command: trust extract-compat
      when:
        - ansible_os_family in ['Archlinux']
  become: true
  when:
    - certs_dir.stat.exists
    - certs_dir.stat.isdir

# --- Archlinux AUR packages ---------------------------------

- name: Configure AUR packages building (Archlinux)
  block:
    - name: create user aur_user to build AUR packages
      ansible.builtin.user:
        name: aur_builder
      become: true

    - name: add user aur_builder to sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
        state: present
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        validate: /usr/sbin/visudo -cf %s
        create: true
      become: true

    - name: Clone paru PKGBUILD
      git:
        repo: https://aur.archlinux.org/paru-bin.git
        dest: "/tmp/paru-bin"
        update: true

    - name: give rights to 'aur_builder' user on compilation files
      ansible.builtin.file:
        dest: "/tmp/paru-bin/"
        owner: aur_builder
        group: aur_builder
        mode: 'u=rwX,g=rX,o=rX'
        recurse: true
      become: true

    - name: Build 'paru'
      command:
        chdir: "/tmp/paru-bin"
        cmd: "makepkg -si --noconfirm"
      become: true
      become_user: aur_builder

    - name: cleaning
      ansible.builtin.file:
        path: "/tmp/paru-bin/"
        state: absent
      become: true
  when: ansible_os_family == 'Archlinux'

# --- python ----------------------------------------------

- name: Ensure pipx is initialised for user
  command: pipx ensurepath
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin"
  become_user: "{{ default_username }}"

# --- entrypoint -----------------------------------------------

- name: Make /.entrypoint.sh executable
  ansible.builtin.file:
    path: /.entrypoint.sh
    mode: '0755'
    owner: root
    group: root
  become: true
