---

- name: Install required packages
  package:
    name: >-
      {{
        (install_packages.archive | default([])) +
        (install_packages.devel   | default([])) +
        (install_packages.python  | default([])) +
        (install_packages.system  | default([])) +
        (install_packages.utils   | default([])) +
        (install_packages.web     | default([])) +
        (install_packages_os      | default([]))
      }}
    state: present
  become: true
