---

- name: Install required packages (common for all OS)
  package:
    name: "{{ install_packages_os_common | flatten }}"
    state: present

- name: Install required packages (OS specific)
  package:
    name: "{{ install_packages | flatten }}"
    state: present

- name: Install audio packages
  package:
    name: "{{ install_gui_packages_drivers | flatten }}"
    state: present

- name: Install openvpn
  ansible.builtin.package:
    name:
      - openvpn
    state: present

- name: Install go
  package:
    name: "{{ install_packages_go | flatten }}"
    state: present

- name: Install Java
  package:
    name: "{{ install_packages_java | flatten }}"
    state: present

- name: Install node JS
  package:
    name: "{{ install_packages_node | flatten }}"
    state: present

- name: Install perl
  package:
    name: "{{ install_packages_perl | flatten }}"
    state: present

- name: Install ruby
  package:
    name: "{{ install_packages_ruby | flatten }}"
    state: present

- name: Install rust
  package:
    name: "{{ install_packages_rust | flatten }}"
    state: present

- name: Install rust
  package:
    name:
      - base-devel
      - fakeroot
    state: present
  when: ansible_distribution == "Archlinux"
