---

# ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ #> /etc/timezone


- name: Get timezone from ipapi.co if TZ is undefined or empty
  ansible.builtin.uri:
    url: https://ipapi.co/timezone
    return_content: yes
  register: timezone_response
  when: TZ is undefined or TZ == None or TZ | length == 0

- name: Set timezone fact
  ansible.builtin.set_fact:
    timezone: "{{ (TZ is defined and TZ != None and TZ | length > 0) | ternary(TZ, timezone_response.content | trim) }}"

- name: Set timezone fact
  ansible.builtin.set_fact:
    timezone: "{{ timezone_response.content | trim }}"

- name: Set system timezone
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    force: yes

- name: Write timezone to /etc/timezone
  ansible.builtin.copy:
    content: "{{ timezone }}\n"
    dest: /etc/timezone
    owner: root
    group: root
    mode: '0644'
