---

- name: Create default user
  user:
    name: "{{ default_username }}"
    uid: "{{ default_user_UID }}"
    shell: "{{ default_user_shell }}"
    groups: sudo
    append: yes
    state: present
  when: ansible_os_family in ['debian', 'redhat']

- name: Create default user
  user:
    name: "{{ default_username }}"
    uid: "{{ default_user_UID }}"
    shell: "{{ default_user_shell }}"
    groups: wheel
    append: yes
    state: present
  when: ansible_os_family in ['Archlinux']

- name: Set sudo to NOPASSWD for this user
  lineinfile:
    path: /etc/sudoers
    line: "{{ default_username }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
  when: ansible_os_family in ['debian', 'redhat']

- name: Set sudo to NOPASSWD for this user (copy file)
  ansible.builtin.template:
    src: sudoers.volund.conf.j2
    dest: "/etc/sudoers.d/90-{{ default_username }}.conf"
    owner: root
    group: root
    mode: '0444'
  when: ansible_os_family in ['Archlinux']
