
name: Volund Build Image Actions

description: Generic steps to build an image using volund

inputs:
  image_name:
    description: "Image name"
    required: true
    default: "base-arch"

  base_distrib:
    description: "Source image distribution"
    required: true
    default: "arch"

  image_role:
    description: "Image role"
    required: true
    default: "base"

  image_version:
    description: "Image version"
    required: true
    default: "0.1.0"

runs:
  using: "composite"
  steps:

    - name: Download Podman (user mode)
      run: |
        New-Item -Path "." -Name "podman" -ItemType "Directory" | Out-Null

        Invoke-WebRequest -Uri "https://github.com/containers/podman/releases/download/v5.5.2/podman-remote-release-windows_amd64.zip" -OutFile "podman/podman.zip"

        Expand-Archive podman/podman.zip -DestinationPath podman

        "${{ github.workspace }}\podman\podman-5.5.2\usr\bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH
      
      shell: powershell
    
    - name: mock environment
      run: |
        New-Item -Path ${env:USERPROFILE} -Name volund -ItemType "Directory" | Out-Null

      shell: powershell

    - name: Build Image
      run: |
        .\volund.ps1 build -Image ${{ inputs.image_name }} -Distribution ${{ inputs.base_distrib }} -Version ${{ inputs.image_version }} -Role ${{ inputs.image_role }}
      shell: powershell

    - name: List Images
      run: .\volund.ps1 lsi
      shell: powershell
