---

- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: Run Helm install script
  command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm

- name: Ensure Helm is installed
  command: helm version
  register: helm_version
  changed_when: false