---

- name: Install k9s
  ansible.builtin.get_url:
    url: https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_amd64.tar.gz
    dest: /tmp/k9s_Linux_amd64.tar.gz
  become: true

- name: Extract k9s binary
  ansible.builtin.unarchive:
    src: /tmp/k9s_Linux_amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/k9s
  become: true

- name: Ensure k9s binary is executable
  ansible.builtin.file:
    path: /usr/local/bin/k9s
    mode: '0755'
  become: true
