---

- name: Install OpenShift CLI (oc)
  ansible.builtin.get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
    dest: /tmp/openshift-client-linux.tar.gz
  become: true

- name: Extract oc binary
  ansible.builtin.unarchive:
    src: /tmp/openshift-client-linux.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/oc
  become: true

- name: Ensure oc binary is executable
  ansible.builtin.file:
    path: /usr/local/bin/oc
    mode: '0755'
  become: true
