
ARG BASE_IMAGE=debian:latest
FROM ${BASE_IMAGE}

# Ensure the path to entrypoint.sh is correct; update as needed
#COPY ./assets/entrypoint.sh /.entrypoint.sh

RUN bash /opt/resources/bin/volund_build_image.sh

USER volund

WORKDIR /workspace

ENTRYPOINT [ "zsh", "/opt/resources/bin/volund_entrypoint.sh" ]
