
ARG BASE_IMAGE=debian:latest
FROM ${BASE_IMAGE}

# Ensure the path to entrypoint.sh is correct; update as needed
COPY ./assets/entrypoint.sh /.entrypoint.sh

RUN bash /opt/resources/build/build_image.sh

USER volund

WORKDIR /workspace

ENTRYPOINT [ "bash", "/.entrypoint.sh" ]
