---
# vars file for devsecops

install_packages:
  - yamllint
  - trivy

oc_client_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz


test_commands:
  - oc version
  - helm version
  - k9s version
  - kubectl version --client
  - stern --version
  - trivy --version
  - yamllint --version

cleanup_temp:
  - helm.tar.gz
  - argocd
  - k9s
  - "linux-{{ binary_arch_name }}" # left by k9s
  - README.md                      # left by k9s
  - LICENSE                        # left by k9s
  - "k9s_Linux_{{ binary_arch_name }}.tar.gz"
  - stern
  - openshift-client-linux.tar.gz
