---
# vars file for devsecops

install_packages:
  - yamllint
  - trivy

oc_client_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz


test_commands:
  - oc version
  - helm version
  - k9s version
  - kubectl version --client
  - stern --version
  - trivy --version
  - yamllint --version
