---
# vars file for devsecops

# list of packages to install on all OS
install_packages:
  - yamllint
  - trivy

# list of commands to execute after install step, to ensure that applications are running properly
test_commands:
  - oc version
  - helm version
  - k9s version
  - kubectl version --client
  - stern --version
  - trivy --version
  - yamllint --version

# list of files to cleanup before/after install step execution
cleanup_temp:
  - helm.tar.gz
  - argocd
  - k9s
  - "linux-{{ binary_arch_name }}" # left by k9s
  - README.md                      # left by k9s
  - LICENSE                        # left by k9s
  - "k9s_Linux_{{ binary_arch_name }}.tar.gz"
  - stern
  - openshift-client-linux.tar.gz

# list of python packages to install with pipx, in user home directory
install_pipx_tools: []

oc_client_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
