---
# tasks file for network_scan

- name: Install required packages (common for all OS)
  package:
    name: "{{ install_packages_os_common | flatten }}"
    state: present

- name: Install required packages (OS specific)
  package:
    name: "{{ install_packages | flatten }}"
    state: present
