---
# tasks file for network_scan

- name: Install required packages (common for all OS)
  package:
    name: >-
      {{
        (install_packages_os_common | default([])) +
        (install_packages | default([]))
      }}
    state: present
  become: true

- name: install Autorecon (https://github.com/Tib3rius/AutoRecon)
  community.general.pipx:
    name: autorecon
    state: present
  when: "'autorecon' in install_packages_os_common"
  become: true
  become_user: "{{ default_username }}"
