---
# tasks file for network_scan

- name: Install required packages (common for all OS)
  package:
    name: "{{ install_packages | flatten }}"
    state: present
  become: true

- name: install Autorecon (https://github.com/Tib3rius/AutoRecon)
  community.general.pipx:
    name: "{{ install_pipx_tools | flatten }}"
    state: present
  become: true
  become_user: "{{ default_username }}"
