name: Build Podman Image

on:
  - push

jobs:
  build:
    # 2025 version is better with SWL2 enabled by default : https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md
    # runs-on: windows-latest
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4

      # Download/Install podman
      - name: Download Podman (user mode)
        run: |
          mkdir podman
          Invoke-WebRequest -Uri "https://github.com/containers/podman/releases/download/v5.0.0/podman-remote-release-windows_amd64.zip" -OutFile "podman/podman.zip"

          write-host "---------------"

          get-childitem -Path podman

          write-host "---------------"

          Expand-Archive podman/podman.zip -DestinationPath podman
        shell: powershell

      # Add podman folder to PATH
      - name: Add Podman to PATH
        run: |
          echo "${{ github.workspace }}\podman\podman-5.0.0\usr\bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH
        shell: powershell

      # (si WSL/Podman Machine déjà initialisé) Build via wrapper
      - name: Build Image via Volund (wrapper PowerShell)
        run: .\volund.ps1 build -Image test -Distribution arch -Version 0.0.1
        shell: powershell

      - name: List Images/Containers
        run: .\volund.ps1 lsi
        shell: powershell
