name: Build Base Debian Image

on:
  - push

jobs:
  build:
    # 2025 version is better with SWL2 enabled by default : https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md
    # runs-on: windows-latest
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4

      - name: Download Podman (user mode)
        run: |
          mkdir podman
          Invoke-WebRequest -Uri "https://github.com/containers/podman/releases/download/v5.5.2/podman-remote-release-windows_amd64.zip" -OutFile "podman/podman.zip"
          Expand-Archive podman/podman.zip -DestinationPath podman
        shell: powershell

      - name: Add Podman to PATH
        run: |
          echo "${{ github.workspace }}\podman\podman-5.5.2\usr\bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH
        shell: powershell

      - name: Build Image
        run: |
          .\volund.ps1 build -Image test -Distribution debian -Version 0.0.1
        shell: powershell

      - name: List Images
        run: .\volund.ps1 lsi
        shell: powershell
