---

install_packages:
  - ca-certificates
  - ca-certificates-utils
  - firefox  # FIXME: extract to web browser list (firefox-esr)
  - procps
  - python-pip
  - python-virtualenv
  - python-pipx
  - which

ca_trust_path: /etc/ca-certificates/trust-source/anchors/

install_gui_packages_drivers:
  - pulseaudio
  - alsa-lib
  - ffmpeg
