---

install_packages:
  - python3-pip
  - python3-venv
  - pipx
  - ca-certificates
  - procps
  - python3
  - sudo
  - vim
  - wget
  - yq

ca_trust_path: /usr/local/share/ca-certificates/

install_packages_go:
  - golang
