---
# tasks file for common_it

- name: Install required packages
  package:
    name: >-
      {{
        (install_packages           | default([])) +
        (install_packages_os_common | default([]))
      }}
    state: present
  become: true
